apiVersion: v1
kind: Service
metadata:
  name: jkk-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: spring-jkk
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
    - protocol: TCP
      port: 3000 #Service port
      targetPort: 8080 #The port for the React.js application container